version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - jar -cvf aws-devops-demo.war *
artifacts:
  files:
    - aws-devops-demo.war
    - .ebextensions/**/*
